### ISSUE TITLE
White list (always allowed phone numbers)

### ISSUE THREAD

**Issue by serrq** [FossifyOrg/Phone#152]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

I need of a white list because I want that safe numbers always have access to incoming calls on phone.

The consequence of this is that I can allow only whitelisted numbers (optionally).

### Why do you want this feature?

Telemarketing and aggressive spam. It always target me.

**Comment by Aga-C** [comment]
You can already set the app to allow only calls from contacts stored in your phone.

**Comment by Astisme** [comment]
I'd also need this feature for pattern matching. @Aga-C 

I've set the app as follows: contacts saved, block all hidden numbers on, block all numbers not in contacts on.

But the other day I needed to receieve a phone call from a business for which I only knew the area code (after the country code).

To make sure I could receive their call, I had to disable the block all numbers not in contacts and wait their call. Meanwhile, I received 3 spam calls (which I knew weren't important due to the prefix not matching) and was really annoying.

Once I finally got the call I was expecting, I then had to go back to the settings to re enable the option to block calls from unknown callers.

---

If i had the white list feature available, I could've simply added this business' area code with a * after it to the list and not have to worry about anything else!

After all, this is not even a weird feature to have since we all have to receive calls from our area of residence from time to time ;)
